// UI strings for the five languages of the original disc
export const LANGS = [
  { code: "en", name: "English" },
  { code: "it", name: "Italiano" },
  { code: "es", name: "Español" },
  { code: "fr", name: "Français" },
  { code: "de", name: "Deutsch" },
];

const S = {
  en: { updateTitle: "Update available", updateBody: "A new version of the app is available.", updateForced: "This version is no longer supported. Please update to continue.", updateNow: "Update now", updateLater: "Later", restored: "Restored from the original 1999/2000 project", readPassage: "Read the passage", chooseLanguage: "Choose your language", journey: "The Journey", places: "holy places · in the order of His life", intro: "Introduction", watchIntro: "Watch the introduction film", photos: "photos", photo: "photo", video: "video", guideVideo: "Guide video", previous: "Previous", next: "Next", map: "Map", videos: "Videos", bible: "Bible", bibleRefs: "Bible references", search: "Search", searchPlaceholder: "Search places and photos", back: "Back", loading: "Loading…", offline: "You are offline — showing saved content.", noResults: "No results", privacy: "Privacy Policy", disclaimer: "Disclaimer", about: "About", contact: "Contact", language: "Language", of: "of", minutes: "min", allPhotos: "All photos", install: "Install app", share: "Share", openIn: "Open", mt: "Matthew", mk: "Mark", lk: "Luke", jn: "John", nextPlace: "Next place", prevPlace: "Previous place", home: "Home", tagline: "A multimedia journey through the Holy Land in five languages", credits: "by Fadi & Sami", seeAll: "See all", fullscreen: "Fullscreen", videoNotAvailable: "Video not available in this language", pageEmpty: "This page has no content yet." },
  it: { updateTitle: "Aggiornamento disponibile", updateBody: "È disponibile una nuova versione dell'app.", updateForced: "Questa versione non è più supportata. Aggiorna per continuare.", updateNow: "Aggiorna ora", updateLater: "Più tardi", restored: "Restaurato dal progetto originale del 1999/2000", readPassage: "Leggi il brano", chooseLanguage: "Scegli la lingua", journey: "Il Viaggio", places: "luoghi santi · nell'ordine della Sua vita", intro: "Introduzione", watchIntro: "Guarda il film introduttivo", photos: "foto", photo: "foto", video: "video", guideVideo: "Video guida", previous: "Precedente", next: "Successivo", map: "Mappa", videos: "Video", bible: "Bibbia", bibleRefs: "Riferimenti biblici", search: "Cerca", searchPlaceholder: "Cerca luoghi e foto", back: "Indietro", loading: "Caricamento…", offline: "Sei offline — contenuti salvati.", noResults: "Nessun risultato", privacy: "Informativa sulla privacy", disclaimer: "Avvertenze", about: "Chi siamo", contact: "Contatti", language: "Lingua", of: "di", minutes: "min", allPhotos: "Tutte le foto", install: "Installa l'app", share: "Condividi", openIn: "Apri", mt: "Matteo", mk: "Marco", lk: "Luca", jn: "Giovanni", nextPlace: "Luogo successivo", prevPlace: "Luogo precedente", home: "Home", tagline: "Un viaggio multimediale in Terra Santa in cinque lingue", credits: "di Fadi & Sami", seeAll: "Vedi tutto", fullscreen: "Schermo intero", videoNotAvailable: "Video non disponibile in questa lingua", pageEmpty: "Questa pagina non ha ancora contenuti." },
  es: { updateTitle: "Actualización disponible", updateBody: "Hay una nueva versión de la aplicación.", updateForced: "Esta versión ya no es compatible. Actualiza para continuar.", updateNow: "Actualizar ahora", updateLater: "Más tarde", restored: "Restaurado del proyecto original de 1999/2000", readPassage: "Leer el pasaje", chooseLanguage: "Elige tu idioma", journey: "El Viaje", places: "lugares santos · en el orden de Su vida", intro: "Introducción", watchIntro: "Ver la película de introducción", photos: "fotos", photo: "foto", video: "vídeo", guideVideo: "Vídeo guía", previous: "Anterior", next: "Siguiente", map: "Mapa", videos: "Vídeos", bible: "Biblia", bibleRefs: "Referencias bíblicas", search: "Buscar", searchPlaceholder: "Buscar lugares y fotos", back: "Volver", loading: "Cargando…", offline: "Sin conexión — mostrando contenido guardado.", noResults: "Sin resultados", privacy: "Política de privacidad", disclaimer: "Aviso legal", about: "Acerca de", contact: "Contacto", language: "Idioma", of: "de", minutes: "min", allPhotos: "Todas las fotos", install: "Instalar la app", share: "Compartir", openIn: "Abrir", mt: "Mateo", mk: "Marcos", lk: "Lucas", jn: "Juan", nextPlace: "Lugar siguiente", prevPlace: "Lugar anterior", home: "Inicio", tagline: "Un viaje multimedia por Tierra Santa en cinco idiomas", credits: "por Fadi & Sami", seeAll: "Ver todo", fullscreen: "Pantalla completa", videoNotAvailable: "Vídeo no disponible en este idioma", pageEmpty: "Esta página aún no tiene contenido." },
  fr: { updateTitle: "Mise à jour disponible", updateBody: "Une nouvelle version de l'application est disponible.", updateForced: "Cette version n'est plus prise en charge. Veuillez mettre à jour pour continuer.", updateNow: "Mettre à jour", updateLater: "Plus tard", restored: "Restauré à partir du projet original de 1999/2000", readPassage: "Lire le passage", chooseLanguage: "Choisissez votre langue", journey: "Le Voyage", places: "lieux saints · dans l'ordre de Sa vie", intro: "Introduction", watchIntro: "Voir le film d'introduction", photos: "photos", photo: "photo", video: "vidéo", guideVideo: "Vidéo guide", previous: "Précédent", next: "Suivant", map: "Carte", videos: "Vidéos", bible: "Bible", bibleRefs: "Références bibliques", search: "Rechercher", searchPlaceholder: "Rechercher des lieux et des photos", back: "Retour", loading: "Chargement…", offline: "Hors ligne — contenu enregistré.", noResults: "Aucun résultat", privacy: "Politique de confidentialité", disclaimer: "Avertissement", about: "À propos", contact: "Contact", language: "Langue", of: "sur", minutes: "min", allPhotos: "Toutes les photos", install: "Installer l'app", share: "Partager", openIn: "Ouvrir", mt: "Matthieu", mk: "Marc", lk: "Luc", jn: "Jean", nextPlace: "Lieu suivant", prevPlace: "Lieu précédent", home: "Accueil", tagline: "Un voyage multimédia en Terre Sainte en cinq langues", credits: "par Fadi & Sami", seeAll: "Tout voir", fullscreen: "Plein écran", videoNotAvailable: "Vidéo non disponible dans cette langue", pageEmpty: "Cette page n'a pas encore de contenu." },
  de: { updateTitle: "Update verfügbar", updateBody: "Eine neue Version der App ist verfügbar.", updateForced: "Diese Version wird nicht mehr unterstützt. Bitte aktualisieren, um fortzufahren.", updateNow: "Jetzt aktualisieren", updateLater: "Später", restored: "Wiederhergestellt aus dem Originalprojekt von 1999/2000", readPassage: "Den Abschnitt lesen", chooseLanguage: "Wähle deine Sprache", journey: "Die Reise", places: "heilige Stätten · in der Reihenfolge Seines Lebens", intro: "Einführung", watchIntro: "Einführungsfilm ansehen", photos: "Fotos", photo: "Foto", video: "Video", guideVideo: "Video-Führung", previous: "Zurück", next: "Weiter", map: "Karte", videos: "Videos", bible: "Bibel", bibleRefs: "Bibelstellen", search: "Suchen", searchPlaceholder: "Orte und Fotos suchen", back: "Zurück", loading: "Wird geladen…", offline: "Offline — gespeicherte Inhalte.", noResults: "Keine Ergebnisse", privacy: "Datenschutzerklärung", disclaimer: "Haftungsausschluss", about: "Über uns", contact: "Kontakt", language: "Sprache", of: "von", minutes: "Min.", allPhotos: "Alle Fotos", install: "App installieren", share: "Teilen", openIn: "Öffnen", mt: "Matthäus", mk: "Markus", lk: "Lukas", jn: "Johannes", nextPlace: "Nächster Ort", prevPlace: "Vorheriger Ort", home: "Start", tagline: "Eine multimediale Reise durch das Heilige Land in fünf Sprachen", credits: "von Fadi & Sami", seeAll: "Alle anzeigen", fullscreen: "Vollbild", videoNotAvailable: "Video in dieser Sprache nicht verfügbar", pageEmpty: "Diese Seite hat noch keinen Inhalt." },
};

export let lang = "en";
export function setLang(l) { lang = LANGS.some((x) => x.code === l) ? l : "en"; localStorage.setItem("discloj.lang", lang); document.documentElement.lang = lang; }
export function savedLang() { return localStorage.getItem("discloj.lang"); }
export const t = (key) => (S[lang] && S[lang][key]) ?? S.en[key] ?? key;
// pick a localized field {en,it,...} with fallback to English then any
export function L(obj) { if (!obj) return ""; if (typeof obj === "string") return obj; return obj[lang] || obj.en || Object.values(obj).find(Boolean) || ""; }
// "1.26-38" -> "1:26-38"
export const fmtRef = (r) => String(r || "").split(";").map((x) => x.trim().replace(".", ":")).filter(Boolean).join(" · ");
